name: Release build

# trigger when github release is created
on:
  release:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # get the code from forked repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # set up node
      - name: Setup Node
      uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # install deps
      - name: Install dependencies
        run: npm ci

      # run dummy tests
      - name: Run unit tests
        run: npm test

  build:
    # only runs if tests passed
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # build placeholder scripts
      - name: Build Android binary
        run: npm run build:android

      - name: Build iOS binary
        run: npm run build:ios

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: volunteam-binaries
          path: ci-build/
